Module TextAnLiteralConstants


    ' Labeling for smart tags
    ' If you want another language, you just have to translate the texts.
    Public Const KPlcPropertiesCategory = "PLC"
    Public Const KPlcAdressingCategory = "PLC Addressing"
    Public Const KPlcFolderCategory = "Folder characteristics"
    Public Const KPlcFormCategory = "Form Characteristics"

    Public Const KPlcComboBoxCategory = "ComboBox characteristics"
    Public Const KPlcPictureBoxCategory = "PictureBox characteristics"
    Public Const KPlcLedCategory = "Led characteristics"
    Public Const KPlcButtonCategory = "Button characteristics"
    Public Const KPlcNumberLabel = "PLC N#"
    Public Const KPlcDataAreaLabel = "Data Area"
    Public Const KPlcDBLabel = "DB N#"
    Public Const KPlcByteLabel = "Byte N#"
    Public Const KPlcItemsLabel = "ComboBox List"
    Public Const KPlcBitLabel = "Bit N#"
    Public Const KPlcBitPictureTrue = "Picture when true"
    Public Const KPlcBitPictureFalse = "Picture when false"
    Public Const KPlcBorderStyle = "Border Style"

    Public Const KPlcShapetypeLabel = "Shape type"
    Public Const KPlcTrueValueLabel = "Color if true"
    Public Const KPlcFalseValueLabel = "Color if false"
    Public Const KFilterLabel = "Filter"
    Public Const KPlcValueTypeLabel = "Value Type"
    Public Const KSaveFolder = "Folder"
    Public Const KExtensionFile = "File extension"
    Public Const KPlcButtonTypeLabel = "Write '1' only if pressed"
    Public Const KPlcButtonCaption = "Button Text"
    Public Const KPlcLengthLabel = "STR Length"
    Public Const KPlcFormActive = "This contros is used in a form"
    Public Const KPlcFormNumber = "Form N#"
    Public Const KPlcLoadForm = "Loading Form"
    Public Const KPlcShapeType = "Shape type"
    Public Const KPlcColorTrue = "Color True"
    Public Const KPlcColorFalse = "Color False"
    Public Const KPlcTipPlcNumber = "Number of PLC configured"
    Public Const KPlcTipDataArea = "Type of PLC Area: inputs, outputs, marks or DB"
    Public Const KFolderSaveTip = "Folder where the form data will be stored"
    Public Const KFolderLoadTip = "Button is used for loading data instead of saving data"
    Public Const KSaveLabel = "RECIPE NAME"
    Public Const KLoadLabel = "RECIPE LIST"
    Public Const KDataSaved = "Data saved!"
    Public Const KFolderNotExist = "Folder does not exist."

    Public Const KExtensionTip = "Extension for stored data file."
    Public Const KSelectFolder = "Select folder"
    Public Const KPlcTipDataType = "Type of data: integers, reals, strings, chars..."
    Public Const KPlcTipPlcDB = "In case of using DB, number of the DB"
    Public Const KPlcTipPlcByte = "Byte in which variable is set"
    Public Const KPlcTipComboboxItems = "ComboBox string items"
    Public Const KPlcTipPlcBit = "Bit for boolean variable"
    Public Const KPlcTipPlcFormActive = "The control is used in a form"
    Public Const KPlcTipPlcFormNumber = "The number of the form where is used"
    Public Const KPlcTipPictureBoxTrue = "Picture for true value"
    Public Const KPlcTipPictureBoxFalse = "Picture for false value"
    Public Const KPlcTipBorderStyle = "Border style"

    Public Const KShowPictureFalseAsDefault = "Show false picture as default"
    Public Const KShowPictureTrueAsDefault = "Show true picture as default"

    Public Const KPlcTipShapeType = "Shape type for led"
    Public Const KPlcTipTrueValue = "Color for true value"
    Public Const KPlcTipFalseValue = "Color for false value"
    Public Const KPlcTipButtonType = "When enabled, the true is sent only if button is being pressed"
    Public Const KPlcTipCaptionType = "Caption"

    Public Const KPlcTipStrLength = "Max. Length of the string (max characters)"

    'General Text
    Public Const KErrorConnectingToPLC1 = "Impossible to connect to PLC: "
    Public Const KRequestRetry = ". Retry the connection?"
    Public Const KErrorConnectionTitle = "Connection error"
    Public Const KErrorIntroducingValue = "Error introducing value."
End Module
